### ISSUE TITLE
MicroBus implementation with RxJava?

### ISSUE THREAD

**Issue by AdamCopperfield** [konmik/MicroBus#1]
Hi, Konmik. 
Could you please show your bus implementation with RxJava instead of MicroBus?
Thanks.

**Comment by konmik** [comment]
Hi, Adam.

There is a possibility to replace the bus pattern with rxjava (google for "replace event bus with rxjava"), but I strongly advise against doing this. If you need to do this - use callbacks, this is a much more reliable pattern.

**Comment by AdamCopperfield** [comment]
Yeah, callbacks it much reliable, but is it suitable for android development and in particular for activity-fragment and fragment-fragment communication?

**Comment by konmik** [comment]
Fragment->fragment or fragment->activity communication can be done like this: https://github.com/konmik/nucleus/blob/master/nucleus-example-with-fragments/src/main/java/nucleus/example/main/FragmentStack.java#L144

You can also inject Lazy objects (that do not exist at the moment of instantiation) with Dagger to call them back later.
